### ISSUE TITLE
MatchTiles Scoring Descrepencies

### ISSUE THREAD

**Issue by Fredenck** [awest25/Tennis-Video-Viewer#114]
Many matches have issues with tiebreaks/other niche areas.

@jerryshi042003 can you link which matches are incorrect and possible reasons why?

Some include:
- Ahmani v. usc
- Kimmi v. OSU
- Bianca v. USC
- Jorge v. UNLV
- AC v. Duke

From what I've investigated so far:
~**FIXED** for Ahmani v use: the last gameScore column in Set 1 was 5 - 3 instead of 5-3.~

for Kimmi v OSU: the setName is wrong for the last few columns
<img width="1433" alt="IMG_1353" src="https://github.com/awest25/Tennis-Video-Viewer/assets/40157329/18deb1ef-7792-422e-ac55-795370fc5f86">

for Bainca v USC: I believe we have a miscalculation in the tiebreak score by 1.

**Comment by kesdlvi** [comment]
Most of the bugs are due to errors in how the match data was entered. Here are the errors I found:

- Kimmi vs osu 
     -Game scores inputted incorrectly (should be 6-4, 5-5 (UF). Best to check firebase and re enter the scores.
- Jorge vs UNLV 
     - Fix Tiebreak for second set (should be 8-10). The final sets also seems to have an issue 
- Ac vs duke 
     - Incomplete data. 

If you like I can try to fix this in the firebase, unless someone would like to do it. 

For the issue with Bianca v. USC, there was a typo in one of the functions dealing with tiebreak scores. I'll commit the changes to that.

**Comment by Fredenck** [comment]
> Most of the bugs are due to errors in how the match data was entered. Here are the errors I found:
> 
> * Kimmi vs osu
>   -Game scores inputted incorrectly (should be 6-4, 5-5 (UF). Best to check firebase and re enter the scores.
> * Jorge vs UNLV
>   
>   * Fix Tiebreak for second set (should be 8-10). The final sets also seems to have an issue
> * Ac vs duke
>   
>   * Incomplete data.
> 
> If you like I can try to fix this in the firebase, unless someone would like to do it.
> 
> For the issue with Bianca v. USC, there was a typo in one of the functions dealing with tiebreak scores. I'll commit the changes to that.

Yes pls! I think we can just ignore Ac vs duke, but if you can fix the rest that'd be great.

Could you also make a PR for the typo and ref this issue with it?
