### ISSUE TITLE
One Filter at a Time

### ISSUE THREAD

**Issue by Fredenck** [awest25/Tennis-Video-Viewer#149]
We want to have each subfilter only be active one at a time. For example, players will not want to look at all their forehands and their backhands at the same time. Clicking on a new one in the same sub-filter deselects the old one.
For Ad, Deuce have it in two layers

<img width="275" alt="image" src="https://github.com/awest25/Tennis-Video-Viewer/assets/40157329/c5fdb265-207b-4646-bfbd-3cc002e3d25f">

**Comment by awest25** [comment]
What's the status on this? Does it need to be worked on?

**Comment by alexanderchen750** [comment]
I'm pretty sure it's not complete. I'm on vacation right now but I can work on it when I get back mid-next week

**Comment by awest25** [comment]
Thanks, Reach out when you're ready to start working as we may have higher-priority tickets we need done before the start of hte quarter
