### ISSUE TITLE
Add new search bar

### ISSUE THREAD

**Issue by awest25** [awest25/Tennis-Video-Viewer#172]
### Function
In the new design for our homepage, we want a search bar that fuzzy searches and filters the displayed matches by any field. For example, looking at the screenshot below, the Kimmy Hance vs. Makaila match, the following should match:
- "Kim"
- "Singles"
- "Texas"
- "04/07"

So search all fields in Firebase to find matches and display them all.

#### Update

And at this point could you make it so that if the player types something it refreshes the tile list each time a new character is added? And when they start typing a cancel button becomes visibe that, when clicked, erases the text box and hides the cancel button and removes the filter.

To facilitate this, the search bar should permanently be ~30px higher, leaving a permanent gap between that and the event list, leaving room for the right-alined cancel button to show up.

### Development
Branch off of development.

Since we're already using react-select, just go ahead and use that, and basically take the useMatchData custom hook to extract match data, and do a fuzzy search through every property of every match (just not the points field). Return an array of matches that fit the critera along with the `property: value` combo that was matched.

This will be used in the match homepage/dashboard #170. Don't worry about rendering anything yet, that will be handled by @tonysjeon in that branch.

### Design
<img width="918" alt="image" src="https://github.com/awest25/Tennis-Video-Viewer/assets/93575706/72d08085-be10-4996-ad87-873f1ad96577">

**Comment by Fredenck** [comment]
closed with PR #181
