### ISSUE TITLE
Make homepage title bar smaller

### ISSUE THREAD

**Issue by awest25** [awest25/Tennis-Video-Viewer#195]
Push the text "BSA | Tennis Consulting" closer to "Dashboard", make the font sizes of both significantly smaller, so the actual content starts closer to the top of the page.

<img width="1505" alt="image" src="https://github.com/user-attachments/assets/6805c94e-d106-4550-966c-7481d564a82e">

### Development
Note that there is already a branch created for this issue (on the right). It is branched from branch `development`. This is our new "main" branch for this sprint but it's not publicly accessible. So even if you aren't completely done, please merge frequently into `development` so everyone else can see your changes. We will merge it into `main` to be hosted when all features in the sprint are done.

When you start working on the issue, immediately create a PR against the `development` branch and link this issue. This way we can see your live progress.

**Comment by tyu-hi** [comment]
issue closed, pushed onto dev with "issue #195" commit
