### ISSUE TITLE
Convert CSV to JSON Automatically

### ISSUE THREAD

**Issue by awest25** [awest25/Tennis-Video-Viewer#2]
When the upload button is pressed, have (probably) the client convert the CSV to JSON so it doesn't manually have to be done.

Also, allow for standard youtube links and just convert them to the embed link automatically.

**Comment by malcyb123** [comment]
Hello, I would like to work on this issue. Please assign me this task!

**Comment by Fredenck** [comment]
deprecated: we'll have tagging directly done through website and saved to Firebase (removing Google Sheets dependency)
