### ISSUE TITLE
Quick Improvements in Internal match tagging page

### ISSUE THREAD

**Issue by jerryshi042003** [awest25/Tennis-Video-Viewer#23]
MOST URGENT: 
1. Add Point Number next to row number so people aren't confused with the timestamp
2. Add Game End Splitter (horizontal line or word that says Game X) such that the points are easily differentiated and the tagger can quickly correct a mistake if poss. It is very easy to remember what point in the game it was but much harder to remember point in the whole match.
3. Change only the display of the milliseconds into hour:minuite. Copy columns should remain ms. 

Added: 

Add clickable link to right of row that says "Click for Point" and it changes timestamp of video to start of the point and either
1. ends where point ends
2. add millisecond timestamp that shows where video is playing 
Goal: so we can reference the end of point timestamp is correct

Not Urgent (front end can be dealt with later)
- The text field for "input youtube code" should be seen in splitscreen (narrow). This is because that's how the taggers normally use it.

**Comment by alexanderchen750** [comment]
1. & 2. For each point, just list 1, 2, 3,
Add a button for ending of game or set
So when a new game, then add a section divider or header that indicates its a new category


3. Visually user sees hours minutes, but data sent is in ms
