### ISSUE TITLE
Front End: Concealing Columns from data

### ISSUE THREAD

**Issue by jerryshi042003** [awest25/Tennis-Video-Viewer#24]
There are some columns like Serve Placement for each point that has rows for when serve goes in but also rows when it doesn't. Currently it's set up to display T, Body, Wide, and Double Fault. However, if possible the Double Fault should not be an option. 

If it makes it easier, we can either manually choose to conceal Double Fault value or change it to None and hide all None values from displaying, which may be necessary as other columns have values that are not meant for every point. like winner type would only be for the shots that are winner so the points that are not winner should not be able to be clicked on with that filter.

Example: isBreakPoint should just have toggle for True, and not for False 

Communicate with other teams, to know the logic on this if you change it.

**Comment by alexanderchen750** [comment]
For example:

Serve Placement: Double Fault's or NA should be concealed from the filterable list
Later on columns like AtNet which have True/False should hide the false option so you can only click when its true

for different columns choose what value to leave out in the codebase
