### ISSUE TITLE
Add Proper Styling

### ISSUE THREAD

**Issue by awest25** [awest25/Tennis-Video-Viewer#3]
In general, we want the left 2/3 of the screen to be taken up by the video and the right 1/3 to be the points list. Maybe use some UCLA colors.

**Comment by aftab2001** [comment]
I believe this will do the work . 

- Used ucla colors.
- video takes 2/3 width.
- fixed the drop down visibility 
- fixes #9  
![ucla_tennis_1](https://github.com/awest25/Tennis-Video-Viewer/assets/73380320/b413dcde-75b1-4037-94ef-8c33edc6c9c5)
![ucla_tennis_2](https://github.com/awest25/Tennis-Video-Viewer/assets/73380320/8d289b31-68c1-4a39-943a-83220c04fc76)
