### ISSUE TITLE
Sort filters by priority

### ISSUE THREAD

**Issue by awest25** [awest25/Tennis-Video-Viewer#30]
- Change the way the /services/nameMap.js file is handled to make it so the filters show up in that order

If this is impossible for some reason:
- create a file /services/filterOrder.js or something. It would be less convenient to have a file for filters to include and another for their order

Remember, we're trying to make it as easy as possible for someone with no programming experience to edit the columns. If the json in nameMap.js shows up exactly as is, this would be ideal.

**Comment by jerryshi042003** [comment]
@tomohto @awest25 I dont understand how the filters are being sorted. They are not being sorted by the order in namemap.js currently

**Comment by tomohto** [comment]
I think it’s because my pull request won’t he changed hasn’t been approved
yet.
