### ISSUE TITLE
Move "active filters" to just above the two columns (points and filters)

### ISSUE THREAD

**Issue by awest25** [awest25/Tennis-Video-Viewer#43]
- Make the active filters more compact
- Make it so they persist when you scroll through both of the lists

**Comment by darishkhan** [comment]
I would like to work on this issue. If possible, could you please detail a bit about the same.

**Comment by kesdlvi** [comment]
This is what I have right now. Styling with the lists does get a bit awkward when you click on multiple filters, I'll see what I can do to make it more compact

https://github.com/awest25/Tennis-Video-Viewer/assets/85363542/4564d900-83e2-4d92-8ec0-a07473311a43

**Comment by darishkhan** [comment]
How about keeping a fixed maximum width for Active filters div and then adding a scroll bar?
