### ISSUE TITLE
Highlight active filters within list

### ISSUE THREAD

**Issue by awest25** [awest25/Tennis-Video-Viewer#44]
- There is no feedback when you select a filter. Active filters should have a little checkmark next to them or change to be a different color.

**Comment by darishkhan** [comment]
I was working on this; I added this feature on a previous version, which I had locally. But when I pulled the latest version, I couldn't see the 'points' section below 'Active Filters.'

**Comment by Fredenck** [comment]
Yes, we are currently reformatting our data collection format which changes our Firebase documents

**Comment by awest25** [comment]
Resolved with #54.
