### ISSUE TITLE
backend: auto-save tagging page

### ISSUE THREAD

**Issue by Fredenck** [awest25/Tennis-Video-Viewer#51]
auto save table data to firestore every x rows

need a way to update the document with new data and delete old data. Can look into Firebase Transactions

Currently separated frontend data by
- old: data from backend (tagging done by someone else or earlier self)
- new: newly added data
- delete: data to be deleted from the BACKEND: this only applies to "old data". The frontend can simply remove the data from "new"

I'm pretty sure I have the backend set up correctly; however, I'm struggling with managing state updates, specifically for:
- handleStartTimeChange/handleEndTimeChange: need to signify if I'm changing "old" or "new" data
    - we still want to be able to delete "old" data in case of previous error
- d/f: I have it so it's just changing "new" data because the current user can only make "new" data ("old" is from the backend). However, State doesn't seem to be updating on React refresh? The issue of being able to spam d is back; addTimeList is never updated?

**Comment by Fredenck** [comment]
see commit 21d1ff1 for latest changes

**Comment by awest25** [comment]
done
