### ISSUE TITLE
Remove empty subfilters. 

### ISSUE THREAD

**Issue by kesdlvi** [awest25/Tennis-Video-Viewer#63]
As brought up by @jerryshi042003, there are empty subfilters for every filter column that need to be removed. 

They can be hovered over and clicked on. 
<img width="285" alt="Screenshot 2024-02-03 at 10 28 28 PM" src="https://github.com/awest25/Tennis-Video-Viewer/assets/85363542/2c83342c-a045-4118-83e4-e6a578b94cd0">

![Image](https://github.com/awest25/Tennis-Video-Viewer/assets/79689407/bdad4eb8-922c-4796-88b7-9938303d4c8d)

**Comment by jerryshi042003** [comment]
> As brought up by @jerryshi042003, there are empty subfilters for every filter column that need to be removed.
> 
> They can be hovered over and clicked on. <img alt="Screenshot 2024-02-03 at 10 28 28 PM" width="285" src="https://private-user-images.githubusercontent.com/85363542/302082022-2c83342c-a045-4118-83e4-e6a578b94cd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzIwNzIsIm5iZiI6MTcwNzI3MTc3MiwicGF0aCI6Ii84NTM2MzU0Mi8zMDIwODIwMjItMmM4MzM0MmMtYTA0NS00MTE4LTgzZTQtZTZhNTc4Yjk0Y2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDAyMDkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZjQxNmNhM2ZhNmZjZTIyMTQ5YmMwZjU3M2QyOTNkYTk2YTFiODk2ODcwOGVkMmI0MTcxMTc0ODJiOTY5YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yQwLKWNrybtxE8H2tRWN5tqkykbjvOMzw09kfM11BEY">

From Jerry: I Believe it's because some data has "" empty substring because it is not related to the column. For example: Serve Placement is Body, T, Wide but if the serve missed (Double Fault) Then the placement is an empty string "". For these cases we just don't want to show empty string as an option.

**Comment by awest25** [comment]
Now, the empty subfilter is at the bottom

**Comment by awest25** [comment]
Fixed somewhere
