### ISSUE TITLE
Make video player resizeable

### ISSUE THREAD

**Issue by awest25** [awest25/Tennis-Video-Viewer#79]
If someone is on a small laptop and they don't really care to see the margins or filter list, it would be nice if they could make the video bigger and just see the point list.

Have to consider at what point does the filter list disappear?

Proposed by @jerryshi042003

**Comment by kesdlvi** [comment]
could this be a toggle/option in the option bar?

**Comment by awest25** [comment]
This functionality will have to wait until our new design is completed.
