### ISSUE TITLE
Figma Review 

### ISSUE THREAD

**Issue by Fredenck** [awest25/Tennis-Video-Viewer#84]
https://www.figma.com/file/YWXYlBgXTF60y8AfMC2LJI/bsa?type=design&node-id=0-1&mode=design

Good:
- points list at bottom is visually nice and tells good information
- filter system
- final score/match-info/matchup
- key stats and visuals: nice and clean; better than embedded pdf
- overall rounded boxes

Improvements:
- Keep points list at bottom, allow manual selection. Points can be jumped to with [next point] and [next selected point]
- Use new filter system: cleaner
- move final score/match0info/matchup or make it smaller: video should be main focus
- embed R Shiny dashboard with key stats/visuals

**Comment by awest25** [comment]
Agreed with everything Fred is saying, but I'm not sure if having the points list underneath the video is a good idea, becuase to get to the "next" point, they would have to scroll down every time to hit the play button next to the following point right?
