### ISSUE TITLE
Make new, more descriptive point list from Figma

### ISSUE THREAD

**Issue by ritzz26** [awest25/Tennis-Video-Viewer#88]
Adding a points list to the bottom of the page and matching the style to the figma design.

Point list preview:
<img width="516" alt="image" src="https://github.com/awest25/Tennis-Video-Viewer/assets/93575706/b614610b-798b-40dc-9d8c-b4069ce59eae">

The UI interaction to get to this point list is being finalized, but for now, just focus on getting the elements to look like they do in the mockup.

**Comment by awest25** [comment]
For now, do not worry about the tabs or "play selected ponts" button. The exact design for this is yet to be finalized. (but please do impliment active filters).

**Comment by ritzz26** [comment]
<img width="707" alt="image" src="https://github.com/awest25/Tennis-Video-Viewer/assets/98070074/74a5492b-a4a2-42b3-b322-265f5fe4f507">

mobile view
