### ISSUE TITLE
Create match description tiles

### ISSUE THREAD

**Issue by awest25** [awest25/Tennis-Video-Viewer#90]
Create the 3 tiles with info about the match exactly as pictured in the Figma.

Here is the figma and a screenshot:
https://www.figma.com/file/rKDwnejQjQVGYFWr3gcPkV/bsa-(Copy)?type=design&node-id=0%3A1&mode=dev&t=AwXqJXVcCHw6haX3-1

<img width="516" alt="image" src="https://github.com/awest25/Tennis-Video-Viewer/assets/93575706/0babdcdd-1878-487b-98e8-01e439467e1b">

**Comment by kesdlvi** [comment]
Right now I am just having trouble figuring out how to get the school images, opposing school name and location of the match. 

I initially tried to parse the match name string, but the different formats of match names makes this tricky. For example: 
"Kimmi Hance vs Malaika Rapolu UCLA (W) vs Texas 1-19"
and 
"Tian Fang Ran UCLA vs. Irina Cantos Siemers Ohio State 2/4/24"

It is a lot easier to retrieve the opposing team name in the first string as it simply follows the "vs". The same issue goes for dates. Some use the "-" format while others use the "/". 

Maybe this could be an issue. It would be beneficial to have all match titles follow a specific format.
