### ISSUE TITLE
Reformat the video and small point list

### ISSUE THREAD

**Issue by awest25** [awest25/Tennis-Video-Viewer#91]
The video player as well as the new point list should have a rounded off design as seen in the figma. Please make it look exactly like shown.

We are still finalizing designs for the "expand" button at the bottom of the small point list, so don't worry about this one button for now. In the future it will slide open the point list to reveal the more detailed one.

Leave a blank rounded off element in the bottom right as a placeholder for the scoreboard that will be made in a seperate issue.

Here is the [figma link](https://www.figma.com/file/rKDwnejQjQVGYFWr3gcPkV/bsa-(Copy)?type=design&node-id=0%3A1&mode=dev&t=AwXqJXVcCHw6haX3-1) and a screenshot:

<img width="858" alt="Screenshot 2024-02-29 at 1 14 08 AM" src="https://github.com/awest25/Tennis-Video-Viewer/assets/93575706/9847bca2-49c3-46e7-89f2-b1232df78c8d">

**Comment by Fredenck** [comment]
outdated
